package dokter;

import AdministrasiRS.*;

import java.awt.*;
import javax.swing.*;
import java.sql.PreparedStatement;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;


import java.sql.PreparedStatement;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;

import java.io.*; 
import java.lang.*; 

/**
 *
 * @author Putri Syalwa
 */
public class listDokterr extends javax.swing.JFrame {

    static Connection con = DBConnection.getConnection();
    /**
     * Creates new form listDokterrrr
     */
    public listDokterr() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        labelHeader = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnaddTindakan = new javax.swing.JButton();
        btnStruck = new javax.swing.JButton();
        field_search = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        labelHeader1 = new javax.swing.JLabel();
        btnAll = new javax.swing.JButton();
        labelHeader2 = new javax.swing.JLabel();
        field_search1 = new javax.swing.JTextField();
        labelHeader3 = new javax.swing.JLabel();
        btnSearch1 = new javax.swing.JButton();
        btnAll1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        btndelDokter = new javax.swing.JButton();
        btnBack1 = new javax.swing.JButton();
        btnupdDokter = new javax.swing.JButton();

        jFrame1.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelHeader.setText("Daftar Riwayat Pendaftaran");
        labelHeader.setFont(new Font("Century Gothic", Font.BOLD, 28));
        labelHeader.setForeground(new Color(119,136,153));
        labelHeader.setBounds(114, 68, 213, 59);
        labelHeader.setHorizontalAlignment(SwingConstants.CENTER);

        btnBack.setText("Kembali");
        btnBack.setBackground(new Color(119,136,153));
        btnBack.setForeground(SystemColor.menu);
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTable1);

        btnaddTindakan.setText("Tambah Tindakan");
        btnBack.setBackground(new Color(119,136,153));
        btnBack.setForeground(SystemColor.menu);
        btnaddTindakan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddTindakanActionPerformed(evt);
            }
        });

        btnStruck.setText("Tampilkan Struk Pembayaran");
        btnBack.setBackground(new Color(119,136,153));
        btnBack.setForeground(SystemColor.menu);
        btnStruck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStruckActionPerformed(evt);
            }
        });

        btnSearch.setText("search");
        btnBack.setBackground(new Color(119,136,153));
        btnBack.setForeground(SystemColor.menu);
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        labelHeader1.setText("Search by no rekam medis");
        //labelHeader.setFont(new Font("Century Gothic", Font.BOLD, 28));
        //labelHeader.setForeground(new Color(119,136,153));
        labelHeader1.setBounds(114, 68, 213, 59);
        labelHeader1.setHorizontalAlignment(SwingConstants.CENTER);

        btnAll.setText("see all");
        btnBack.setBackground(new Color(119,136,153));
        btnBack.setForeground(SystemColor.menu);
        btnAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAllActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame1Layout.createSequentialGroup()
                .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jFrame1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(labelHeader, javax.swing.GroupLayout.DEFAULT_SIZE, 660, Short.MAX_VALUE))
                    .addGroup(jFrame1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnBack)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
            .addGroup(jFrame1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(btnaddTindakan)
                .addGap(37, 37, 37)
                .addComponent(btnStruck)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jFrame1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelHeader1)
                    .addGroup(jFrame1Layout.createSequentialGroup()
                        .addComponent(field_search, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnAll)
                            .addComponent(btnSearch))))
                .addGap(29, 29, 29))
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelHeader)
                .addGap(50, 50, 50)
                .addComponent(labelHeader1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSearch)
                    .addComponent(field_search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAll)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnaddTindakan)
                    .addComponent(btnStruck))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 106, Short.MAX_VALUE)
                .addComponent(btnBack)
                .addGap(28, 28, 28))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelHeader2.setText("List Dokter");
        labelHeader2.setFont(new Font("Century Gothic", Font.BOLD, 28));
        labelHeader2.setForeground(new Color(119,136,153));
        labelHeader2.setBounds(114, 68, 213, 59);
        labelHeader2.setHorizontalAlignment(SwingConstants.CENTER);

        labelHeader3.setText("Search by ID Dokter");
        //labelHeader.setFont(new Font("Century Gothic", Font.BOLD, 28));
        //labelHeader.setForeground(new Color(119,136,153));
        labelHeader1.setBounds(114, 68, 213, 59);
        labelHeader1.setHorizontalAlignment(SwingConstants.CENTER);

        btnSearch1.setText("search");
        btnSearch1.setBackground(new Color(119,136,153));
        btnSearch1.setForeground(SystemColor.menu);
        btnSearch1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearch1ActionPerformed(evt);
            }
        });

        btnAll1.setText("see all");
        btnAll1.setBackground(new Color(119,136,153));
        btnAll1.setForeground(SystemColor.menu);
        btnAll1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAll1ActionPerformed(evt);
            }
        });

        Object[][] tempp = Query.getListDokter();
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            tempp,
            new String [] {
                "ID Dokter", "Nama Dokter", "No Izin Praktek","Tgl Mulai", "Phone Number", "Spesialisasi", "ID Poliklinik", "Alamat","Gaji"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        btndelDokter.setText("Delete Dokter");
        btndelDokter.setBackground(new Color(119,136,153));
        btndelDokter.setForeground(SystemColor.menu);
        btndelDokter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndelDokterActionPerformed(evt);
            }
        });

        btnBack1.setText("Kembali");
        btnBack1.setBackground(new Color(119,136,153));
        btnBack1.setForeground(SystemColor.menu);
        btnBack1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBack1ActionPerformed(evt);
            }
        });

        btnupdDokter.setText("Update Dokter");
        btnupdDokter.setBackground(new Color(119,136,153));
        btnupdDokter.setForeground(SystemColor.menu);
        btnupdDokter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdDokterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelHeader3)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(field_search1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnAll1)
                            .addComponent(btnSearch1))))
                .addGap(29, 29, 29))
            .addComponent(jScrollPane2)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelHeader2, javax.swing.GroupLayout.DEFAULT_SIZE, 667, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnBack1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnupdDokter)
                                .addGap(50, 50, 50)
                                .addComponent(btndelDokter)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelHeader2)
                .addGap(50, 50, 50)
                .addComponent(labelHeader3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSearch1)
                    .addComponent(field_search1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAll1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btndelDokter)
                    .addComponent(btnupdDokter))
                .addGap(32, 32, 32)
                .addComponent(btnBack1)
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnaddTindakanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddTindakanActionPerformed
//        updateDokter start = new updateDokter();
//        start.run();
//        this.setVisible(false);
    }//GEN-LAST:event_btnaddTindakanActionPerformed

    private void btnStruckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStruckActionPerformed
        
    }//GEN-LAST:event_btnStruckActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        String noRM =field_search1.getText();
        Object[][] tempp = Query.getListSearchDokter(noRM);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            tempp,
            new String [] {
                "ID Dokter", "Nama Dokter", "No Izin Praktek", "Phone Number", "Spesialisasi", "Gaji", "ID Poliklinik"
            }
        ));
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAllActionPerformed
        Object[][] tempp = Query.getListDokter();

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            tempp,
            new String [] {
                "ID Dokter", "Nama Dokter", "No Izin Praktek","Tgl Mulai", "Phone Number", "Spesialisasi", "ID Poliklinik", "Alamat","Gaji"
            }
        ));
    }//GEN-LAST:event_btnAllActionPerformed

    private void btnSearch1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearch1ActionPerformed
        String noRM =field_search1.getText();
        Object[][] tempp = Query.getListSearchDokter(noRM);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            tempp,
            new String [] {
                "ID Dokter", "Nama Dokter", "No Izin Praktek","Tgl Mulai", "Phone Number", "Spesialisasi", "ID Poliklinik", "Alamat","Gaji"
            }
        ));
    }//GEN-LAST:event_btnSearch1ActionPerformed

    private void btnAll1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAll1ActionPerformed
        Object[][] tempp = Query.getListDokter();

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            tempp,
            new String [] {
                "ID Dokter", "Nama Dokter", "No Izin Praktek", "Phone Number", "Spesialisasi", "Gaji", "ID Poliklinik"
            }
        ));
    }//GEN-LAST:event_btnAll1ActionPerformed

    private void btndelDokterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndelDokterActionPerformed
        delDokterr start = new delDokterr();
        start.run();
        this.setVisible(false);
    }//GEN-LAST:event_btndelDokterActionPerformed

    private void btnBack1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBack1ActionPerformed
        viewDokter start = new viewDokter();
        start.run();
        this.setVisible(false);
    }//GEN-LAST:event_btnBack1ActionPerformed

    private void btnupdDokterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdDokterActionPerformed
       dokterID start = new dokterID();
        start.run();
        this.setVisible(false);
    }//GEN-LAST:event_btnupdDokterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(listDokterr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(listDokterr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(listDokterr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(listDokterr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new listDokterr().setVisible(true);
        });
        
    }
    
    public void run() {
        listDokterr calcu = new listDokterr();
        calcu.getContentPane().setBackground(new Color(204,229,255));
        calcu.setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAll;
    private javax.swing.JButton btnAll1;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnBack1;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnSearch1;
    private javax.swing.JButton btnStruck;
    private javax.swing.JButton btnaddTindakan;
    private javax.swing.JButton btndelDokter;
    private javax.swing.JButton btnupdDokter;
    private javax.swing.JTextField field_search;
    private javax.swing.JTextField field_search1;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JLabel labelHeader;
    private javax.swing.JLabel labelHeader1;
    private javax.swing.JLabel labelHeader2;
    private javax.swing.JLabel labelHeader3;
    // End of variables declaration//GEN-END:variables
}
