package pendaftaran;

/**
 *
 * @author DZAKIRA
 */
import AdministrasiRS.*;
import pendaftaran.*;
import java.awt.*;
import javax.swing.*;


public class viewPendaftaranForAdmin extends javax.swing.JFrame {

    /**
     * Creates new form viewPendaftaran
     */
    public viewPendaftaranForAdmin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelHeader = new javax.swing.JLabel();
        btnListPendaftaran = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        btnListRJalan = new javax.swing.JButton();
        btnListRInap1 = new javax.swing.JButton();
        btnListRInapSkrg1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Administrasi RS DPR");

        labelHeader.setText("Kelola Data Riwayat Pendaftaran");
        labelHeader.setFont(new Font("Century Gothic", Font.BOLD, 28));
        labelHeader.setForeground(new Color(119,136,153));
        labelHeader.setBounds(114, 68, 213, 59);
        labelHeader.setHorizontalAlignment(SwingConstants.CENTER);

        btnListPendaftaran.setText("List R. Pendaftaran");
        btnListPendaftaran.setBackground(new Color(119,136,153));
        btnListPendaftaran.setFont(new Font("Century Gothic", Font.BOLD, 18));
        btnListPendaftaran.setForeground(SystemColor.menu);
        btnListPendaftaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListPendaftaranActionPerformed(evt);
            }
        });

        btnBack.setText("Kembali");
        btnBack.setBackground(new Color(119,136,153));
        btnBack.setForeground(SystemColor.menu);
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnListRJalan.setText("List R. Jalan");
        btnListRJalan.setBackground(new Color(119,136,153));
        btnListRJalan.setFont(new Font("Century Gothic", Font.BOLD, 18));
        btnListRJalan.setForeground(SystemColor.menu);
        btnListRJalan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListRJalanActionPerformed(evt);
            }
        });

        btnListRInap1.setText("List R. Inap");
        btnListRInap1.setBackground(new Color(119,136,153));
        btnListRInap1.setFont(new Font("Century Gothic", Font.BOLD, 18));
        btnListRInap1.setForeground(SystemColor.menu);
        btnListRInap1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListRInap1ActionPerformed(evt);
            }
        });

        btnListRInapSkrg1.setText("List Rawat Inap Saat Ini");
        btnListRInapSkrg1.setBackground(new Color(119,136,153));
        btnListRInapSkrg1.setFont(new Font("Century Gothic", Font.BOLD, 14));
        btnListRInapSkrg1.setForeground(SystemColor.menu);
        btnListRInapSkrg1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListRInapSkrg1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(btnBack))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnListRInap1, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE)
                            .addComponent(btnListPendaftaran, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnListRInapSkrg1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnListRJalan, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)))
                    .addComponent(labelHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 461, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(labelHeader)
                .addGap(148, 148, 148)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnListPendaftaran, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnListRInapSkrg1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnListRJalan, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnListRInap1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 196, Short.MAX_VALUE)
                .addComponent(btnBack)
                .addGap(29, 29, 29))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnListPendaftaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListPendaftaranActionPerformed
        listPendaftaranForAdmin start = new listPendaftaranForAdmin  ();
        start.run();
        this.setVisible(false);
    }//GEN-LAST:event_btnListPendaftaranActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        MainMenuAdmin start = new MainMenuAdmin();
        start.run();
        this.setVisible(false);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnListRJalanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListRJalanActionPerformed
        listRawatJalan start = new listRawatJalan();
        start.run();
        this.setVisible(false);
    }//GEN-LAST:event_btnListRJalanActionPerformed

    private void btnListRInap1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListRInap1ActionPerformed
        listRawatInap start = new listRawatInap();
        start.run();
        this.setVisible(false);
    }//GEN-LAST:event_btnListRInap1ActionPerformed

    private void btnListRInapSkrg1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListRInapSkrg1ActionPerformed
       DaftarInapSkrg start = new DaftarInapSkrg();
        start.run();
        this.setVisible(false);
    }//GEN-LAST:event_btnListRInapSkrg1ActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(viewPendaftaranForAdmin .class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(viewPendaftaranForAdmin .class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(viewPendaftaranForAdmin .class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(viewPendaftaranForAdmin .class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new viewPendaftaranForAdmin ().setVisible(true);
        });
        
        
    }
    
    public void run() {
                viewPendaftaranForAdmin  calcu = new viewPendaftaranForAdmin ();
                calcu.getContentPane().setBackground(new Color(204,229,255));
                calcu.setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnListPendaftaran;
    private javax.swing.JButton btnListRInap1;
    private javax.swing.JButton btnListRInapSkrg1;
    private javax.swing.JButton btnListRJalan;
    private javax.swing.JLabel labelHeader;
    // End of variables declaration//GEN-END:variables
}
