/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package keuangan;

import AdministrasiRS.*;
import java.awt.*;
import java.sql.PreparedStatement;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;


import java.io.*; 
import java.lang.*; 
import java.sql.CallableStatement;

/**
 *
 * @author DZAKIRA
 */
public class strukResult extends javax.swing.JFrame {

    String noRegis = "";
    String tarif = "";
    /**
     * Creates new form strukResult
     */
    public strukResult(String aNoRegis, String aTarif){
        this.tarif = aTarif;
        this.noRegis = aNoRegis;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        field_bulan = new javax.swing.JLabel();
        labelHeader = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        field_biaya = new javax.swing.JLabel();

        field_bulan.setForeground(new Color(119,136,153));
        field_bulan.setBounds(114, 68, 213, 59);
        field_bulan.setHorizontalAlignment(SwingConstants.CENTER);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelHeader.setText("Struk Pembayaran");
        labelHeader.setFont(new Font("Century Gothic", Font.BOLD, 28));
        labelHeader.setForeground(new Color(119,136,153));
        labelHeader.setBounds(114, 68, 213, 59);
        labelHeader.setHorizontalAlignment(SwingConstants.CENTER);

        btnBack.setText("Kembali");
        btnBack.setBackground(new Color(119,136,153));
        btnBack.setForeground(SystemColor.menu);
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        Object[][] tempp = struck.getListTindakan(noRegis);
        //Object[][] tempp = new Object[8][8];
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            tempp,
            new String [] {
                "Nama Tindakan", "Tarif", "Jumlah", "Total"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        field_biaya.setForeground(new Color(119,136,153));
        field_biaya.setBounds(114, 68, 213, 59);
        field_biaya.setHorizontalAlignment(SwingConstants.CENTER);
        field_biaya.setText("Total tarif : " + tarif);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnBack)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(50, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(field_biaya, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addGap(45, 45, 45))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(labelHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 169, Short.MAX_VALUE)
                .addComponent(field_biaya, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62)
                .addComponent(btnBack)
                .addGap(25, 25, 25))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(labelHeader)
                    .addContainerGap(491, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        strukPembayaran start = new  strukPembayaran ();
        start.run();
        this.setVisible(false);
    }//GEN-LAST:event_btnBackActionPerformed

//   public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(strukResult.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(strukResult.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(strukResult.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(strukResult.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(() -> {
//            new strukResult().setVisible(true);
//        });
//        
//    }
    
    public void run(String aNoRegis, String aTarif){
        strukResult calcu = new strukResult(aNoRegis, aTarif);
        calcu.getContentPane().setBackground(new Color(204,229,255));
        calcu.setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JLabel field_biaya;
    private javax.swing.JLabel field_bulan;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel labelHeader;
    // End of variables declaration//GEN-END:variables
}


class struck { 
    static Connection con = DBConnection.getConnection();

    static Object[][] getListTindakan(String idP){
      
      PreparedStatement pst = null;
      PreparedStatement pst2 = null;
      PreparedStatement pst3 = null;
      
      
      String sql2 = "select rp_no_registrasi FROM PEMBAYARAN WHERE id_pembayaran = '" + idP +"'" ;
      System.out.println(sql2);
      ResultSet st, st2, st3;
      int size = 0;
      Object[][] result =  new Object[0][0];
      Object[][] result2 =  new Object[1][1];
        
        try {
            
            pst2 = con.prepareStatement(sql2);
            
            st2=pst2.executeQuery();
            int i=0;
            while(st2.next()){
                    result2[i][0] = st2.getString(1);  
            }
            
            String sql = "select id_tindakan,tarif,jumlah,total from TINDAKAN_HISTORY WHERE no_registrasi = '" + result2[0][0] +"'" ;
            pst = con.prepareStatement(sql);
            
            st=pst.executeQuery();
            while(st.next()){
                size++;
            }
            result =  new Object[size][4];
            
            st=pst.executeQuery();
            i=0;
            while(st.next()){
                for (int k =1; k<5 ;k++){
                    result[i][k-1] = st.getString(k);
                }
                String sqlNamaTindakan = "select * from TINDAKAN WHERE id_tindakan = '" + st.getString(1) +"'" ;
                pst3 = con.prepareStatement(sqlNamaTindakan);

                st3=pst3.executeQuery();
                
                int j = 0;
                while(st3.next()){
                    result[i][0] = st3.getString(2);
                }
                
                i++;
            }
            
            pst.close();
            
        } catch (SQLException ex) {
            Logger.getLogger(struck.class.getName()).log(Level.SEVERE, null, ex);
         
        }  
        return result;
        
    }
    
}