-------------------------------------DAFTAR PROCEDURE-------------------------------------
-- PROCEDURE INSERT SETIAP TABEL





------------------------------------------------------------------------------------------


--------------------------PRCEDURE CRUD (Create Read Update Delete)-----------------------

----------------------- INSERT -----------------------
create or replace PROCEDURE POLIKLINIK_INSERT (
    I_NAMA_POLIKLINIK IN POLIKLINIK.NAMA_POLIKLINIK%TYPE)
IS
BEGIN
    INSERT INTO POLIKLINIK("ID_POLIKLINIK","NAMA_POLIKLINIK","JML_DOKTER")
    VALUES('PLKNK', I_NAMA_POLIKLINIK, 0);
    COMMIT;
END;


create or replace PROCEDURE DOKTER_INSERT (
    I_NAMA_DOKTER IN DOKTER.NAMA_DOKTER%TYPE,
    I_NO_IZIN_PRAKTEK IN DOKTER.NO_IZIN_PRAKTEK%TYPE,
    I_PHONE_NUMBER IN DOKTER.PHONE_NUMBER%TYPE,
    I_SPESIALISASI IN DOKTER.SPESIALISASI%TYPE,
    I_GAJI IN DOKTER.GAJI%TYPE,
    I_ALAMAT IN DOKTER.ALAMAT%TYPE,
    I_POLIKLINIK_ID_POLIKLINIK IN DOKTER. POLIKLINIK_ID_POLIKLINIK%TYPE)
IS
BEGIN
    INSERT INTO DOKTER("ID_DOKTER","NAMA_DOKTER","NO_IZIN_PRAKTEK","PHONE_NUMBER","SPESIALISASI","GAJI","ALAMAT","POLIKLINIK_ID_POLIKLINIK", "TGL_MULAI")
    VALUES('DKTR',I_NAMA_DOKTER,I_NO_IZIN_PRAKTEK,I_PHONE_NUMBER,I_SPESIALISASI,I_GAJI, I_ALAMAT, I_POLIKLINIK_ID_POLIKLINIK, SYSDATE );
    COMMIT;    
END;


create or replace PROCEDURE PASIEN_INSERT (
    I_NAMA_PASIEN IN PASIEN.NAMA_PASIEN%TYPE,
    I_GENDER IN PASIEN.GENDER%TYPE, 
    I_TGL_LAHIR IN PASIEN.TGL_LAHIR%TYPE,
    I_ALAMAT IN PASIEN.ALAMAT%TYPE)
IS
BEGIN
    INSERT INTO PASIEN("NO_REKAM_MEDIS","NAMA_PASIEN","GENDER","TGL_LAHIR", "ALAMAT")
    VALUES('P',I_NAMA_PASIEN,I_GENDER,I_TGL_LAHIR, I_ALAMAT);
COMMIT;
END;

create or replace PROCEDURE RIWAYAT_PENDAFTARAN_INSERT (
    I_NO_ANTRI IN ANTRIAN.NO_ANTRI%TYPE, 
    I_SYMPTOM IN RIWAYAT_PENDAFTARAN.SYMPTOM%TYPE, 
    I_DIAGNOSA IN RIWAYAT_PENDAFTARAN.DIAGNOSA%TYPE,
    I_TIPE_RAWAT IN RIWAYAT_PENDAFTARAN.TIPE_RAWAT%TYPE,
    I_PASIEN_NO_REKAM_MEDIS IN RIWAYAT_PENDAFTARAN.PASIEN_NO_REKAM_MEDIS%TYPE,
    I_POLIKLINIK_ID_POLIKLINIK IN RIWAYAT_PENDAFTARAN.POLIKLINIK_ID_POLIKLINIK%TYPE,
    I_DOKTER_ID_DOKTER IN RIWAYAT_PENDAFTARAN.POLIKLINIK_ID_POLIKLINIK%TYPE)
IS
    noreg  RIWAYAT_PENDAFTARAN.NO_REGISTRASI%TYPE;
BEGIN
    INSERT INTO RIWAYAT_PENDAFTARAN("NO_REGISTRASI","SYMPTOM","DIAGNOSA","TIPE_RAWAT","TGL_REGISTRASI","PASIEN_NO_REKAM_MEDIS","POLIKLINIK_ID_POLIKLINIK", "DOKTER_ID_DOKTER")
    VALUES('R',I_SYMPTOM, I_DIAGNOSA, I_TIPE_RAWAT, SYSDATE, I_PASIEN_NO_REKAM_MEDIS, I_POLIKLINIK_ID_POLIKLINIK, I_DOKTER_ID_DOKTER );
    COMMIT;
    
    SELECT NO_REGISTRASI INTO noreg FROM RIWAYAT_PENDAFTARAN 
    WHERE PASIEN_NO_REKAM_MEDIS = I_PASIEN_NO_REKAM_MEDIS AND DOKTER_ID_DOKTER = I_DOKTER_ID_DOKTER;
    
    INSERT INTO ANTRIAN("NO_ANTRI", "NO_REGISTRASI","TGL_REGISTRASI","POLIKLINIK_ID_POLIKLINIK", "DOKTER_ID_DOKTER")
    VALUES(I_NO_ANTRI,noreg, SYSDATE, I_POLIKLINIK_ID_POLIKLINIK, I_DOKTER_ID_DOKTER );
    COMMIT;
END;

create or replace PROCEDURE TINDAKAN_INSERT (
    I_NAMA_TINDAKAN IN TINDAKAN.NAMA_TINDAKAN%TYPE,
    I_DESKRIPSI IN TINDAKAN.DESKRIPSI%TYPE,
    I_TARIF IN TINDAKAN.TARIF%TYPE)
IS
BEGIN
    INSERT INTO TINDAKAN("ID_TINDAKAN","NAMA_TINDAKAN","DESKRIPSI", "TARIF")
    VALUES('T', I_NAMA_TINDAKAN, I_DESKRIPSI, I_TARIF);
    COMMIT;
END;


create or replace PROCEDURE TINDAKAN_HISTORY_INSERT (
    I_NO_REGISTRASI IN TINDAKAN_HISTORY.NO_REGISTRASI%TYPE,
    I_ID_TINDAKAN IN TINDAKAN_HISTORY.ID_TINDAKAN%TYPE,
    I_JUMLAH IN TINDAKAN_HISTORY.JUMLAH%TYPE
    )
IS
    I_TARIF TINDAKAN.TARIF%TYPE;
BEGIN
    SELECT tarif INTO I_TARIF FROM TINDAKAN WHERE ID_TINDAKAN = I_ID_TINDAKAN;
    INSERT INTO TINDAKAN_HISTORY("NO_REGISTRASI", "ID_TINDAKAN", "JUMLAH","TOTAL_TARIF")
    VALUES(I_NO_REGISTRASI, I_ID_TINDAKAN, I_JUMLAH, (I_JUMLAH*I_TARIF));
    COMMIT;
END;

create or replace PROCEDURE RESEP_INSERT (
    I_NO_REG IN RESEP.NO_REGISTRASI%TYPE,
    I_KETERANGAN IN RESEP.KETERANGAN%TYPE)
IS
BEGIN
    INSERT INTO RESEP("ID_RESEP", "NO_REGISTRASI", "KETERANGAN", "TGL_RESEP", "STATUS_TEBUS")
    VALUES('MP', I_NO_REG, I_KETERANGAN, SYSDATE, 'BELUM DITEBUS');
    COMMIT;
END;

create or replace PROCEDURE OBAT_INSERT (
    I_KODE_OBAT IN OBAT.KODE_OBAT%TYPE,
    I_NAMA_OBAT IN OBAT.NAMA_OBAT%TYPE,
    I_STOCK_FISIK IN OBAT.STOCK_FISIK%TYPE,
    I_HARGA IN OBAT.HARGA%TYPE,
    I_ID_JENIS_OBAT IN OBAT.ID_JENIS_OBAT%TYPE)
IS
BEGIN
    INSERT INTO OBAT("ID_OBAT", "KODE_OBAT", "NAMA_OBAT", "STOCK_FISIK", "STOCK_AVAILABLE", "HARGA", "ID_JENIS_OBAT")
    VALUES('O', I_KODE_OBAT, I_NAMA_OBAT, I_STOCK_FISIK, I_STOCK_FISIK, I_HARGA, I_ID_JENIS_OBAT);
    COMMIT;
END;

create or replace PROCEDURE INGREDIENT_INSERT (
    I_NAMA_BAHAN IN INGREDIENT.NAMA_BAHAN%TYPE)
IS
BEGIN
    INSERT INTO ingredient("ID_BAHAN", "NAMA_BAHAN")
    VALUES('I', I_NAMA_BAHAN);
    COMMIT;
END;

create or replace PROCEDURE KANDUNGAN_OBAT_INSERT (
    I_ID_OBAT IN KANDUNGAN_OBAT.ID_OBAT%TYPE,
    I_ID_BAHAN IN KANDUNGAN_OBAT.ID_BAHAN%TYPE)
IS
    I_NAMA_OBAT KANDUNGAN_OBAT.NAMA_OBAT%TYPE;
    I_NAMA_BAHAN KANDUNGAN_OBAT.NAMA_BAHAN%TYPE;
BEGIN
    SELECT NAMA_OBAT INTO I_NAMA_OBAT FROM OBAT WHERE ID_OBAT = I_ID_OBAT;
    SELECT NAMA_BAHAN INTO I_NAMA_BAHAN FROM INGREDIENT WHERE ID_BAHAN = I_ID_BAHAN;
    INSERT INTO KANDUNGAN_OBAT("ID_OBAT", "NAMA_OBAT", "ID_BAHAN", "NAMA_BAHAN")
    VALUES(I_ID_OBAT,I_NAMA_OBAT, I_ID_BAHAN, I_NAMA_BAHAN);
    COMMIT;
END;

create or replace PROCEDURE RESEP_OBAT_INSERT (
    I_ID_RESEP IN RESEP_OBAT.ID_RESEP%TYPE,
    I_ID_OBAT IN RESEP_OBAT.ID_OBAT%TYPE,
    I_JUMLAH IN RESEP_OBAT.JUMLAH%TYPE,
    I_UNIT IN RESEP_OBAT.UNIT%TYPE)
IS
    HARGA OBAT.HARGA%TYPE;
BEGIN
    SELECT HARGA INTO HARGA FROM OBAT WHERE ID_OBAT = I_ID_OBAT;
    INSERT INTO RESEP_OBAT("ID_RESEP", "ID_OBAT", "JUMLAH", "UNIT", "TOTAL_HARGA")
    VALUES(I_ID_RESEP, I_ID_OBAT, I_JUMLAH, I_UNIT, (I_JUMLAH * HARGA) );
    COMMIT;
END;


----------------------- UPDATE-----------------------
create or replace PROCEDURE PEMBAYARAN_UPDATE_SUDAH_BAYAR (
    D_ID_PEMBAYARAN IN PEMBAYARAN.ID_PEMBAYARAN%TYPE)
IS
        jml_hari number; 
        tgl_dtg date;
        no_regis pembayaran.rp_no_registrasi%TYPE;
        tipe riwayat_pendaftaran.tipe_rawat%TYPE;
BEGIN
    SELECT rp_no_registrasi INTO no_regis FROM PEMBAYARAN WHERE (ID_PEMBAYARAN =  D_ID_PEMBAYARAN);
    SELECT tipe_rawat INTO tipe FROM riwayat_pendaftaran WHERE no_registrasi = no_regis;
    IF(tipe = 'INAP') THEN
            SELECT tgl_registrasi INTO tgl_dtg FROM RIWAYAT_PENDAFTARAN WHERE no_registrasi = no_regis;    
            SELECT TRUNC(TO_NUMBER(SYSDATE - TO_DATE(tgl_dtg))) INTO jml_hari FROM DUAL;
            jml_hari := jml_hari -1;
                    IF jml_hari >= 0 THEN
                    -- Tambahin Biaya Rawat Inap Dari Awal sampai Akhir
                    -- Biaya Perhari 100000
                    -- ID harus disesuakan dengan ID Tdk Rawat Inap
                        UPDATE TINDAKAN_HISTORY
                       SET jumlah = jumlah + jml_hari,
                            total_tarif = total_tarif + (100000*jml_hari)
                        WHERE id_tindakan = 'T0000002' 
                              AND no_registrasi = no_regis;
                    END IF;
    END IF;


    UPDATE PEMBAYARAN
    SET STATUS_PEMBAYARAN = 'SUDAH DIBAYAR'
    WHERE (ID_PEMBAYARAN =  D_ID_PEMBAYARAN);
    COMMIT;
END;

create or replace PROCEDURE DOKTER_UPDATE (
    D_ID_DOKTER IN DOKTER.ID_DOKTER%TYPE,
    D_NAMA_DOKTER IN DOKTER.NAMA_DOKTER%TYPE,
    D_NO_IZIN_PRAKTEK IN DOKTER.NO_IZIN_PRAKTEK%TYPE,
    D_PHONE_NUMBER IN DOKTER.PHONE_NUMBER%TYPE,
    D_SPESIALISASI IN DOKTER.SPESIALISASI%TYPE,
    D_GAJI IN DOKTER.GAJI%TYPE,
    I_ALAMAT IN DOKTER.ALAMAT%TYPE,
    D_POLIKLINIK_ID_POLIKLINIK IN DOKTER.POLIKLINIK_ID_POLIKLINIK%TYPE)
IS
BEGIN
    UPDATE DOKTER
    SET NAMA_DOKTER = D_NAMA_DOKTER,
        NO_IZIN_PRAKTEK = D_NO_IZIN_PRAKTEK,
        PHONE_NUMBER = D_PHONE_NUMBER,
        SPESIALISASI = D_SPESIALISASI,
        GAJI = D_GAJI,
        ALAMAT = I_ALAMAT,
        POLIKLINIK_ID_POLIKLINIK = D_POLIKLINIK_ID_POLIKLINIK
    WHERE (ID_DOKTER = D_ID_DOKTER);
    COMMIT;
END;

create or replace PROCEDURE DIAGNOSA_UPDATE (
    D_ID_RP IN RIWAYAT_PENDAFTARAN.NO_REGISTRASI%TYPE,
    D_DIAGNOSA IN RIWAYAT_PENDAFTARAN.DIAGNOSA%TYPE)
IS
BEGIN
    UPDATE RIWAYAT_PENDAFTARAN
    SET DIAGNOSA = D_DIAGNOSA
    WHERE (NO_REGISTRASI = D_ID_RP);
    COMMIT;
END;

create or replace PROCEDURE STOCK_OBAT_UPDATE (
    D_ID_OBAT IN OBAT.ID_OBAT%TYPE,
    D_STOCK_FISIK IN OBAT.STOCK_FISIK%TYPE,
    D_STOCK_AVAILABLE IN OBAT.STOCK_AVAILABLE%TYPE)
IS
BEGIN
    UPDATE OBAT
    SET STOCK_FISIK = D_STOCK_FISIK,
        STOCK_AVAILABLE = D_STOCK_AVAILABLE
    WHERE (ID_OBAT = D_ID_OBAT);
    COMMIT;
END;

create or replace PROCEDURE RESEP_OBAT_UPDATE (
    D_ID_RSP IN RESEP_OBAT.ID_RESEP%TYPE,
    D_ID_OBAT IN RESEP_OBAT.ID_OBAT%TYPE,
    D_JUMLAH IN RESEP_OBAT.JUMLAH%TYPE)
IS
BEGIN
    UPDATE RESEP_OBAT
    SET ID_RESEP = D_ID_RSP,
        ID_OBAT = D_ID_OBAT,
        JUMLAH = D_JUMLAH
    WHERE (ID_RESEP = D_ID_RSP);
    COMMIT;
END;


create or replace PROCEDURE TEBUS_RESEP (
    D_ID_RESEP IN RESEP.ID_RESEP%TYPE)
IS
        jml_hari number; 
        tgl_dtg date;
        no_regis pembayaran.rp_no_registrasi%TYPE;
        tipe riwayat_pendaftaran.tipe_rawat%TYPE;
BEGIN
    UPDATE RESEP
    SET STATUS_TEBUS = 'SUDAH DITEBUS'
    WHERE (ID_RESEP =  D_ID_RESEP);
    COMMIT;
END;
----------------------- DELETE -----------------------
create or replace PROCEDURE DOKTER_DELETE (
    D_ID_DOKTER IN DOKTER.ID_DOKTER%TYPE)
IS
BEGIN
    DELETE DOKTER WHERE ID_DOKTER =  D_ID_DOKTER;
    COMMIT;
END;